database(`CREATE TABLE IF NOT EXISTS ENDERECO (
    CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    RUA VARCHAR(45) NOT NULL, 
    BAIRRO VARCHAR(45) NOT NULL,
    CIDADE VARCHAR(45) NOT NULL,
    ESTADO VARCHAR(45) NOT NULL
)`)
    .then(result => {
        console.log('TABELA ENDERECO CRIADA COM SUCESSO');
    }).catch(erro => {
        console.log('ERRO AO CRIAR A TABELA ENDERECO');
    });


database(`CREATE TABLE IF NOT EXISTS PESSOA (
        CPF CHAR(11) PRIMARY KEY,
        NOME VARCHAR(45) NOT NULL,
        IDADE INT
        ENDERECO_CODIGO INT NOT NULL,
        FOREIGN KEY (ENDERECO_CODIGO) REFERENCES ENDERECO(CODIGO) ON DELETE CASCADE ON UPDATE CASCADE)`)
    .then(result => {
        console.log('TABELA PESSOA CRIADA COM SUCESSO');
    }).catch(erro => {
        console.log('ERRO AO CRIAR A TABELA PESSOA');
    });


database(`CREATE TABLE IF NOT EXISTS CLIENTE (
    CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(100),
    USERNAME VARCHAR(45) NOT NULL, 
    PASSWORD VARCHAR(15) NOT NULL,
    PESSOA_CPF CHAR(11) NOT NULL,
    FOREIGN KEY (PESSOA_CPF) REFERENCES PESSOA(CPF))`)
    .then(result => {
        console.log('TABELA CLIENTE CRIADA COM SUCESSO');
    }).catch(erro => {
        console.log('ERRO AO CRIAR A TABELA CLIENTE');
    });


database(`CREATE TABLE IF NOT EXISTS CLASSE (
    CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    CLASSE VARCHAR(45) NOT NULL
)`)
    .then(result => {
        console.log('TABELA CLASSE CRIADA COM SUCESSO');
    }).catch(erro => {
        console.log('ERRO AO CRIAR A TABELA CLASSE');
    });


database(`CREATE TABLE IF NOT EXISTS PRODUTO (
    CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    MARCA VARCHAR(45) NOT NULL,
    VALOR VARCHAR(45) NOT NULL,
    COR VARCHAR(45) NOT NULL,
    CLASSE_CODIGO INT NOT NULL,
    CLIENTE_CODIGO INT NOT NULL,
    FOREIGN KEY (CLASSE_CODIGO) REFERENCES CLASSE(CODIGO) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (CLIENTE_CODIGO) REFERENCES CLIENTE(CODIGO) ON DELETE CASCADE ON UPDATE CASCADE)`)
    .then(result => {
        console.log('TABELA PRODUTO CRIADA COM SUCESSO');
    }).catch(erro => {
        console.log('ERRO AO CRIAR A TABELA PRODUTO');
    });